modLoader="javafml"
loaderVersion="${loaderForgeV}"
issueTrackerURL="${issuesUrl}"
license="${license}"


[[mods]]
modId="${modId}"
version="${modV}"
displayName="${modName}"
displayURL="${curseUrl}"
logoFile= "${modId}.png"
authors="${modAuthors}"
description='''${modDesc}'''


[[dependencies.${modId}]]
modId="forge"
mandatory=true
versionRange="${loaderForgeVRange}"
ordering="NONE"
side="BOTH"

[[dependencies.${modId}]]
modId="minecraft"
mandatory=true
versionRange="[${mcV}]"
ordering="NONE"
side="BOTH"

[[dependencies.${modId}]]
modId="ohmega"
mandatory=true
versionRange="${ohmegaVRange}"
ordering="BEFORE"
side="BOTH"
