modLoader="javafml"
loaderVersion="${loader_version_range}"
license="MIT"
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="Totem Accessory"
logoFile= "${mod_id}.png"
authors="${mod_authors}"
description='''Allows Totems to be equipped as an accessory (Ohmega API)'''
[[dependencies.${mod_id}]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"
[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
[[dependencies.${mod_id}]]
modId="ohmega"
mandatory=true
versionRange="${ohmega_version_range}"
ordering="BEFORE"
side="BOTH"
